// Self-hosts the brand webfonts.
//
// Downloads the Google Fonts CSS for the five brand families, pulls every
// woff2 subset it references into public/fonts/, and writes the matching
// @font-face rules to src/styles/fonts.css with local URLs.
//
// Why not just link fonts.googleapis.com? The PNG export (src/lib/dom-to-png.ts)
// rasterises the card through an SVG <foreignObject>, and an SVG loaded as an
// image cannot fetch anything — every font has to be inlined as a data URI
// first. That only works if the exporter can read the @font-face rules and
// fetch the files, which a cross-origin stylesheet blocks (CSSOM SecurityError
// on `cssRules`). Same-origin fonts make the export deterministic and offline-
// proof, and drop a render-blocking third-party request from every page.
//
// Run after changing the family list:  npm run gen:fonts
import { createHash } from 'node:crypto';
import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

// Keep in sync with the families used in src/styles/vg.css (--font-*) and the
// inline styles baked into the template canvases.
const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Unbounded:wght@400;600;800;900&family=Oswald:wght@500;600;700&family=Sedgwick+Ave+Display&family=IBM+Plex+Sans:ital,wght@0,400;0,500;0,600;1,400&family=IBM+Plex+Mono:wght@400;500&display=swap';

// Google serves woff2 only to browsers that advertise support.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const root = process.cwd();
const outDir = join(root, 'public', 'fonts');
const cssOut = join(root, 'src', 'styles', 'fonts.css');

const slug = (family) =>
  family
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts CSS ${res.status}`);
const css = await res.text();

await mkdir(outDir, { recursive: true });
for (const file of await readdir(outDir).catch(() => [])) {
  if (file.endsWith('.woff2')) await rm(join(outDir, file));
}

// Google prefixes every @font-face with a `/* subset */` comment; keep it so
// the generated file stays readable (and so the exporter's log makes sense).
const blocks = [...css.matchAll(/(?:\/\* ([\w-]+) \*\/\s*)?@font-face \{([^}]*)\}/g)];
if (!blocks.length) throw new Error('no @font-face blocks in the Google CSS');

const downloaded = new Map(); // remote url -> local filename
let bytes = 0;
const out = [];

for (const [, subset = 'default', body] of blocks) {
  const family = /font-family: '([^']+)'/.exec(body)?.[1];
  const remote = /url\((https:\/\/[^)]+)\)/.exec(body)?.[1];
  if (!family || !remote) throw new Error(`unparsable @font-face:\n${body}`);

  let local = downloaded.get(remote);
  if (!local) {
    const fileRes = await fetch(remote, { headers: { 'User-Agent': UA } });
    if (!fileRes.ok) throw new Error(`${remote} -> ${fileRes.status}`);
    const buf = Buffer.from(await fileRes.arrayBuffer());
    const hash = createHash('sha256').update(buf).digest('hex').slice(0, 8);
    local = `${slug(family)}-${subset}-${hash}.woff2`;
    await writeFile(join(outDir, local), buf);
    downloaded.set(remote, local);
    bytes += buf.length;
  }

  out.push(
    `/* ${family} · ${subset} */\n@font-face {${body.replace(/url\(https:\/\/[^)]+\)/, `url(/fonts/${local})`)}}`
  );
}

const header = `/* GENERATED by scripts/gen-fonts.mjs — do not edit by hand.
   Source: ${CSS_URL}
   Fonts are self-hosted so the /templates + /brand PNG export can inline them
   as data URIs (see src/lib/dom-to-png.ts). Regenerate with: npm run gen:fonts */\n\n`;

await writeFile(cssOut, header + out.join('\n\n') + '\n');
console.log(
  `${blocks.length} @font-face rules · ${downloaded.size} files · ${(bytes / 1024).toFixed(0)} KB -> public/fonts/`
);
